ClusterLabs/booth

- GNUmakefile
- script/booth-keygen
- script/ocf/booth-site
- script/ocf/geo_attr.sh
- script/ocf/geostore
- script/ocf/sharedrsc
- src/attr.c
- src/attr.h
- src/auth.c
- src/auth.h
- src/booth.h
- src/config.c
- src/config.h
- src/handler.c
- src/handler.h
- src/inline-fn.h
- src/log.h
- src/main.c
- src/pacemaker.c
- src/pacemaker.h
- src/raft.c
- src/raft.h
- src/request.c
- src/request.h
- src/ticket.c
- src/ticket.h
- src/timer.c
- src/timer.h
- src/transport.c
- src/transport.h
Based on https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
as of today.
> maint: fix the FSF address + 5x s/write the/write to the/

- docs/Makefile.am
- src/attr.c
- src/attr.h
- src/auth.c
- src/auth.h
- src/booth.h
- src/config.c
- src/config.h
- src/handler.c
- src/handler.h
- src/inline-fn.h
- src/log.h
- src/main.c
- src/pacemaker.c
- src/pacemaker.h
- src/raft.c
- src/raft.h
- src/request.c
- src/request.h
- src/ticket.c
- src/ticket.h
- src/timer.c
- src/timer.h
- src/transport.c
- src/transport.h
Once we got clarified "GPLv2.1+ -> GPLv2+" (rejecting LGPL
interpretation, cf. e294fa2), we ought to reword "library"
references to say "program", in accordance to the standard
GPLv2 notice.
In the same vein, da90d0b missed an instance of the old FSF
address, so get this resolved as well.
> maint: licensing conformance follow-up (library->program)

- src/main.c
Also, ensure the variable is just within the file scope (not used
in any other compilation unit).
> fixup: sanitize true-false logic for "daemonize"

- test/assertions.py
- test/serverenv.py
- test/servertests.py
- test/utils.py
Work in progress, do not pull yet.
> unit tests: making them passing

- src/alt/logging_libqb.c
- src/alt/logging_libqb.h
- src/alt/nametag_libsystemd.c
- src/alt/nametag_libsystemd.h
- src/alt/range2random_glib.c
- src/alt/range2random_glib.h
Embarrassingly enough, I forgot to update the PR with the fixed license
notices while I was pushing for clarifications elsewhere in the code.
> maint: clarify GPLv2+ in the license notices from an earlier PR

- script/unit-test.py
In function _filename of class UT, there are two returns, and the
second one will never be executed. Remove one line of return in the
fix.
> low:fix:remove unnecessary return from unit-test.py

- booth.spec
In line 140 of booth.spec, there is "install -m 644 %{S:2}", but
when build booth on SLE12 or openSUSE Leap42.1, it reports %{SOURCE2}
is not defined. I guess the file should be contrib/geo-cluster.fwd.
This patch can fix the build error.
> typo fix: there is no %{S:2} defined in booth.spec

- .travis.yml
This is so as to counterweight unfortunate change
https://github.com/travis-ci/travis-cookbooks/commit/6c575d5d55c08e3a0c046dc7de2aa5d5b38e0b63
that made proper hostnames be mapped from 127.0.1.1 address rather than
127.0.0.1 (properly assigned to loopback interface), hence (likely)
caused "hostname -i" return that other address that is normally not
assigned to loopback (and hence booth cannot identify "itself" within
configured sites, leading to spurious test suite failure).
> CI: travis: workaround 127.0.1.1 not assigned with loopback

- src/config.c
Currently, booth fails to handle hostnames provided in booth.conf file. The changes proposed in this ticket will allow users to specify the sites as hostnames, instead of having to use IP addresses.
After resolving the hostname, the handling of the received IP address is the same as before.
> Configuration: handle hostnames in booth.conf file

- Makefile.am
- booth.spec
- configure.ac
- src/main.c
At present, booth doesn't set the working directory itself. If it is linked with cluster-glue, the working directory is changed by cluster-glue. Otherwise, if we use libqb, nothing takes care of that. As a result, we have problems with creating temporary files and core dumps.
The changes in this pull request are about creating the active directory /var/lib/booth/cores during installation and setting it during startup, if the application is not linked with cluster-glue.
> Build: create and set working directory

- src/ticket.c
Warning produced with GCC 7.1.0:
```
ticket.c: In function ‘process_tickets’:
ticket.c:470:44: warning: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size 53 [-Wformat-truncation=]
snprintf(buff, sizeof(buff), "granted to %s",
^~
ticket.c:470:3: note: ‘snprintf’ output between 12 and 75 bytes into a destination of size 64
snprintf(buff, sizeof(buff), "granted to %s",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
site_string(tk->leader));
~~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix GCC-7 warning on buffer size

- src/transport.c
For some commands, like _booth grant_, _booth list_, or _booth peers_, Booth stopped to look for a local IP address, after finding an address which was 'similar enough'.
This resulted in a ticket being granted to a wrong site, after issuing _booth grant ticketName_ command. Also, the outputs of _booth list_ and _booth peers_ commands were incorrect.
The fix proposed in this pull request improves Booth behavior: after finding an IP address, which in not an exact match, but which is the best possible 'similar address', we will continue to look for an exact IP address (but ignoring any other possible 'similar addresses').
> Determine the correct address of a local site

- docs/boothd.8.txt
- src/main.c
- test/boothrunner.py
- test/serverenv.py
- test/servertests.py
As discussed in [Issue 61](https://github.com/ClusterLabs/booth/issues/61), this change will disable moving Booth to foreground, when debug output is enabled.
We need this change to allow using debug mode in Booth instances acting as HA resources.
> Booth Daemon Arguments: disable foreground for D flag

- src/main.c
As advised in a [previous pull request](https://github.com/ClusterLabs/booth/pull/62), I removed stderr flag from daemon mode.
> Disable stderr for daemon mode

- conf/booth-arbitrator.service.in
The current arbitrator (boothd) has never ended abnormally, but it's safer to set it up.
> Low: conf: Add Restart option to booth-arbitrator.service

- configure.ac
After the last commits, booth has been failing to build for me when asciidoctor was not present.
The line "MANPAGE_GENERATOR += $(ASCIIDOCTOR) -b manpage" was trying to be executed, but with no asciidoctor present on my machine.
I changed the comparisons in configure.ac, to detect a2x and asciidoc in the same way as for other variables, and it works fine now.
> Fix asciidoc build

- conf/Makefile.am
Removing the service.in files breaks the next build attempt.
> Fix cleanup of service.in files

- docs/boothd.8.txt
This was (likely) exposed with asciidoctor being updated to v2.0.0+
resulting in this "visual" (as in actually viewing the man page) diff
before vs. after:
> -       ticket="manual-ticket"
> -           [...]
> -           mode = manual
> -           [...]
> +       ticket="manual-ticket" [...] mode = manual [...]
Marking that part as a literal block (in an established manner)
restores the sanity.
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>
> docs: boothd.8: fix runaway formatting for what's config file snippet

- src/pacemaker.h
/usr/bin/ld: boothd-ticket.o:./src/pacemaker.h:35: multiple definition of `pcmk_handler'; boothd-main.o:./src/pacemaker.h:35: first defined here
/usr/bin/ld: boothd-pacemaker.o:./src/pacemaker.h:35: multiple definition of `pcmk_handler'; boothd-main.o:./src/pacemaker.h:35: first defined here
/usr/bin/ld: boothd-handler.o:./src/pacemaker.h:35: multiple definition of `pcmk_handler'; boothd-main.o:./src/pacemaker.h:35: first defined here
/usr/bin/ld: boothd-attr.o:./src/pacemaker.h:35: multiple definition of `pcmk_handler'; boothd-main.o:./src/pacemaker.h:35: first defined here
> Fix gcc-10 warnings for multiple definition of pcmk_handler

- script/unit-test.py.in
- test/boothtestenv.py
- test/runtests.py.in
This is second (from two parts) part of split (and finalize) of PR #77 . Makes possible to run tests as a root.
Alternative approach (empty lockfile is considered as non-existing) is stated in the second commit and I'm happy to implement it if current solution is not accepted (and I'm open to other solutions as well).
> Allow running tests as a root

- test/boothrunner.py
- test/clientenv.py
- test/serverenv.py
During RPM build I've seen check section failing on highly loaded machine.
So I've tried to reproduce the problem and fix it. As a reproducer I was using 800 `while true;do true;done` cycles and was able to get quite reliable failing of test.
Proposed patches don't enlarge time of running of the test (it actually shorten it, because of second patch which removes hardcoded `sleep(1)`)
> Test running on highly loaded machine - false negatives

- src/booth.h
transport.c: In function ‘booth_tcp_open’:
transport.c:656:42: warning: taking address of packed member of ‘struct booth_site’ may result in an unaligned pointer value [-Waddress-of-packed-member]
656 |  rv = connect_nonb(s, (struct sockaddr *)&to->sa6, to->saddrlen, 10);
|                                          ^~~~~~~~
transport.c: In function ‘message_recv’:
transport.c:1108:7: warning: taking address of packed member of ‘struct booth_site’ may result in an unaligned pointer value [-Waddress-of-packed-member]
1108 |  time(&source->last_recv);
|       ^~~~~~~~~~~~~~~~~~
main.c: In function ‘format_peers’:
main.c:230:14: warning: taking address of packed member of ‘struct booth_site’ may result in an unaligned pointer value [-Waddress-of-packed-member]
230 | …
> Fix gcc-10 warnings for packed struct members

- test/utils.py
Debian is storing 127.0.1.1 address into /etc/hosts for local hostname.
Booth function find_myself is unable to find such address and fails.
Solution is based on using connect on udp socket and reading local
address.
> tests: Make test work for Debian systems

- src/Makefile.am
Patch 4205de05fe337d1b1127fae302e6e6c2f0613ccf introduced better way to
check for pacemaker headers but also usage of PCMK_LIBS when linking
boothd.
This is not needed, because boothd uses just crm/services.h header file
for inclusion of OCF return codes, so patch removes the use of PCMK_LIBS.
> build: Do not link with pcmk libraries

- src/pacemaker.c
crm_ticket included since Pacemaker version 2.0.0-rc2 doesn't return
EPERM (1) error code any longer when ticket is updated without using
--force. Instead new value CRM_EX_INSUFFICIENT_PRIV (4) is used.
This return value is used in the test_atomicity function which is
failing with new enough Pacemaker.
Solution is to check also for return code 4.
Also previously when unexpected code is returned, log contained full
return value as returned by system call. This is not very readable so
use only exit status (WEXITSTATUS) instead.
> pacemaker: Handle updated exit code of crm_ticket

- README-testing
- test/boothtestenv.py.in
- test/runtests.py.in
- test/serverenv.py
- test/utils.py
To allow running multiple instances of tests in parallel only few
changes were needed:
- Do not killall boothd on start
- Do not call ensure_boothd_not_running and rely on cleanup mechanism of
tests itself (works quite well). Another advantage is not rely on
(deprecated) netstat and perl one-liner.
- Generate "unique" port for each of the instance (based on PID)
This patch is (mostly) to allow building rpm (check section) on both i686
and x86_64 when only one physical machine is used (example reproducer is
Fedora Koji) for both architectures.
I was also thinking about having unique port for each test case where
working_config is needed, but such solution was more collisions prone
(and more invasive) than one port per tests instance.
> tests: Allow parallel running of tests

- src/main.c
- src/pacemaker.c
- src/transport.c
None of the problem is critical (booth is really in nice shape in this respect), but I think it make sense to have them fixed. Result of this PR is https://ci.kronosnet.org/job/booth-build-covscan/booth-build-covscan=coverity/16/consoleText. There are 3 warnings left, but it is really just coverity totally ignoring the call of `check_max_len_valid`
> Fix problems found by coverity

- test/live_test.sh
bash 4.4 no longer splits the expansion of here-strings, (see the CHANGES
file of the bash-4.4.beta).
> test: fix the delimiter in the here-string

- test/boothtestenv.py.in
ensure_boothd_not_running is now exectured only when single instance is
used, but if so, it requires netstat command. Netstat is deprecated for
some time and it is slowly disappearing from distributions, so add
support for iproute ss command.
Parameters for both ss and netstat are same, but sadly output differs so
both netstat and ss output is matched.
> test: Add compatibility with iproute ss command

- booth.spec.in
Previously the release was set to 1.$numcomm.$sha1.$dirty.$dist.
This is suboptimal for downstream, because when release increases then
downstream version is always newer no matter what numcomm is. So when CI
tries to install upstream version it won't get installed.
Proposed solution is to use $numcomm.$release.$sha1.$dirty.git.$dist so
numcomm is now second most important (version is first one) making any
pushed version bigger than any downstream version.
This scheme also works with rpmdev-bumpspec because release is now
global variable (rpmdev-bumpspec will increase "%global release" rather
than the release field).
> booth.spec: Change naming scheme for upgrades

- configure.ac
- src/config.c
gethostbyname and inet_ntoa are deprecated and shouldn't be used. Also
gethostbyname is unable to handle ipv6.
Replace gethostbyname by getaddrinfo.
inet_ntoa is replaced by inet_ntop.
> config: Remove deprecated net functions

- test/serverenv.py
Test of file existence and size > 0 seems to be not reliable enough so
mimic behavior of get_daemon_pid_from_lock_file.
(hopefully solves CI failures)
> test: Enhance wait_for_lock_file

- src/main.c
This reverts commit da79b8ba28ad4837a0fee13e5f8fb6f89fe0e24c.
authfile != authkey
Solves #114
> Revert "Refactor: main: substitute is_auth_req macro"

- booth.spec.in
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>
> rpm: use new package name for pacemaker devel on opensuse

- src/ticket.c
malloc expects size_t typed variable so change `alloc` to size_t.
> ticket: Fix compiler warning

- configure.ac
... to make 2.71 happy. Also increase minimum version to 2.69 (10 years
old version so should be compatible enough).
@dmuhamedagic Also during preparing this patch I've found that it is impossible to compile code when BUILD_TIMER_C is unset (so platform without clock_gettime). Fix shouldn't be so hard, but I'm wondering if it does make any sense to support such platforms (and have extra, probably untested ifdef)? Would you accept patch which would make clock_gettime required and remove ifdef with code for platforms without clock_gettime? It wouldn't be super huge code saver, but it removes some lines (and - especially - (probably) untested ifdef part of code).
> configure: Modernize configure.ac a bit

- conf/booth@.service.in
Recent change in systemd made imposible to enable booth@.service any longer - more details in BZ
https://bugzilla.redhat.com/show_bug.cgi?id=2128998. Solution is to delete Alias directive.
> unit file: Remove Alias directive

- src/config.c
- test/servertests.py
Main idea is to improve error message during parsing a bit by adding keyword into "Unexpected/unknown keyword" error message. So instead of:
```
error: Unexpected keyword in config file line 9
```
it shows
```
Unexpected keyword "some-unknown-keyword" in config file line 9
```
Similar is done for transport value so instead of:
```
invalid transport protocol in config file line 8
```
it shows
```
invalid transport protocol "UDP2" in config file line 8
```
Last patch adds test for this functionality.
> Enhance config file error msg

- .gitignore
- docs/booth-keygen.8.txt
- docs/boothd.8.txt
- docs/geostore.8.txt
Series of patches to improve look of how generated man pages (and html files).
Pre/post files can be viewed at https://honzaf.fedorapeople.org/booth-man-asciidoc/asciidoc-pre/ (without patches generated by asciidoc), https://honzaf.fedorapeople.org/booth-man-asciidoc/asciidoc-post/ (with patches generated by asciidoc), https://honzaf.fedorapeople.org/booth-man-asciidoc/asciidoctor-pre/ (without patches generated by asciidoctor), https://honzaf.fedorapeople.org/booth-man-asciidoc/asciidoctor-post/ (with patches generated by asciidoctor). It was really tempting to screenshot console with man page ;) but I've rather decided to use groff and convert man page to html (`for i in *.8;do groff  -mandoc -Thtml "$i" > "$i-groff.html";done`).
Patches have (I hope) quite good description but some …
> Improve asciidoc man pages

- booth.spec.in
Both Fedora and openSUSE now recommends to use SPDX shortname format for License.
> spec: Migrate to SPDX license

- src/main.c
Client command grant/revoke was returning success exit code on some failures (site not configured, arbitrator, no tickets given). Test case is running
`booth grant -s $IP; echo $?`, where IP is not configured in the config file.
Patch fixes this behavior so error code is returned.
> main: Fix exit code on grant/revoke command error

- src/attr.c
attr_get and attr_list were allocation GString but they were calling g_string_free with second argument set to FALSE, what means GLib was returning character data to caller (see g_string_free for complete documentation) instead of freeing them. This return value was ignored by attr_* functions so memory leaked.
Patch to fix this problem is simple - just set second argument of g_string_free to TRUE so GLib takes care of freeing all data.
(found by newest gcc in Fedora rawhide which displays warning)
> attr: Fix memory leak for list and get operation

- src/attr.c
Ticket attribute hash table is created only when some attribute exists. If it doesn't, list and get operations were producing glib assert.
Patch adds check in attr_get and attr_list so hash table is used only when it has been initialized.
> attr: Fix glib hash_table != NULL assert

- test/boothtestenv.py.in
Python 3.12 warns about invalid escape sequence '\s'. It is still correctly converted, but I guess it is better to escape '\' character properly to avoid future breakage.
> tests: Fix Python 3.12 warning

- Makefile.am
make distcheck calls configure script with --prefix to allow installation to tmp directory. ocfdir is not using ${prefix} and instead contains absolute path (either taken from resource-agents.pc or hardcoded one) so make install fails when running as non-root user.
Solution is taken from pacemaker project and it relies on setting AM_DISTCHECK_CONFIGURE_FLAGS so --with-ocfdir is added with directory where user has write permissions.
Big thanks to Fabio M. Di Nitto <fdinitto@redhat.com> for finding this solution.
> build: Make distcheck work for non-root user

- src/pacemaker.c
This can be useful to find out if ticket is managed by booth and what specific booth instance. So cluster configuration tools can delete CIB ticket when removing ticket from booth configuration.
Fixes #135
> pacemaker: Store booth-cfg-name attribute

- src/attr.c
- src/auth.c
Fix reading of server_reply. Also properly check result of gcry_md_get_algo_dlen.
This two patches fixes CVE-2024-3049
Already preaproved by @clumens
> Gcrypt fix

- src/config.c
- src/handler.c
- src/main.c
- src/raft.c
- src/ticket.c
- src/ticket.h
- src/transport.c
These are the first couple patches from #82.  I'm hoping to continue slowly working my way through them over time.  I'm also curious to see what tests get run on a pull request and if anything needs to be changed, so here's a simple one to play with.
> Apply foreach macro refactorings

- src/alt/nametag_libsystemd.c
- src/attr.c
- src/main.c
- src/ticket.c
- src/transport.c
* Several strings are initialized to some value, immediately followed by a block of code that sets them to some other value.  The original initialization can go away.
* Warn if vsnprintf fails.
* Get rid of setting a couple return values that are never checked.
* In read_client, set msg to 0 if we malloc'd it so that header->length is an initialized value when we access it later on.
* In _find_myself, check that tb[IFA_ADDRESS] is not NULL before accessing it.  I'm not sure what we can do if both this and tb[IFA_LOCAL] are NULL aside from log and return.
> Refactor: Fix problems found by clang.

- src/config.c
- src/config.h
- src/main.c
- src/ticket.c
- src/ticket.h
Continuing with #82, this is the next couple patches that address the use of global variables in config.[ch].  I made a couple changes to the original patches - get rid of `_ptr` from the variable names, add braces around conditional blocks in code that this touches, and removing a function instead of marking it as unused.
I tested this only briefly, by installing updated packages and making sure that booth started and could grant tickets.
Note - this builds on top of #147 so that needs to be merged first, then I'll rebase this one and it can be merged as well.
> Apply config.c refactorings

- src/attr.c
- src/attr.h
- src/booth.h
- src/config.c
- src/config.h
- src/handler.c
- src/main.c
- src/manual.c
- src/pacemaker.c
- src/pacemaker.h
- src/raft.c
- src/ticket.c
- src/ticket.h
- src/transport.c
- src/transport.h
This is the next batch of refactorings from PR #82, though there are a couple differences from what's in those patches:
* Note the FOREACH_NODE -> _FOREACH_NODE stuff.  Basically, I renamed it and added a new version that takes an additional config pointer argument so I don't have to update all callers everywhere at once, along with all their callers, and so on.
* These patches built, but would crash because message_recv has a new parameter, but that function is only ever indirectly called through function pointers, and the use of those pointers did not pass the config pointer.  So, various other places had to get that argument added.  I did not check very hard to see how this gets handled in the original PR in later patches.
* I added a function pointer type to simplify having to deal …
> Apply find_* function refactorings

- src/attr.c
- src/booth.h
- src/main.c
- src/manual.c
- src/manual.h
- src/raft.c
- src/raft.h
- src/request.c
- src/request.h
- src/ticket.c
- src/ticket.h
- src/transport.c
- src/transport.h
This one got a little out of control, unfortunately, due to all the networking related functions that call each other.  However, there's nothing tricky going on here.  It's just adding a parameter all over the place.
> Remove global variable from notify_client
